/* Modelo Lógico: */

CREATE TABLE USUARIO (
    CPF VARCHAR2(11),
    NOME VARCHAR2(100),
    EMAIL VARCHAR2(150),
    SENHA VARHCAR2(50),
    TIPO_USER NUMBER(1),
    ID_USER NUMBER(6) PRIMARY KEY,
    ENDERECO NUMBER(6),
    UNIQUE (CPF, EMAIL)
);

CREATE TABLE VEICULO (
    ID_VEICULO NUMBER(6) PRIMARY KEY,
    MODELO NUMBER(6),
    ANO_FAB NUMBER,
    FK_CONECTOR NUMBER(6),
    PLACA VARCHAR2(10) UNIQUE,
    FK_COR NUMBER(6),
    FK_USUARIO_ID_USER NUMBER(6)
);

CREATE TABLE PONTO_CARREGAMENTO (
    ID_PONTO NUMBER(6) PRIMARY KEY,
    LOCALIZACAO NUMBER(6),
    VALOR_KWH NUMBER,
    TEMPO_MEDIO_REC TIME,
    DISPONIBILIDADE NUMBER(6)
);

CREATE TABLE PARADA_ROTA (
    DESCRICAO VARCHAR2(100),
    LOCALIZACAO NUMBER(6),
    NOME VARHCAR2(100),
    ID_PARADA NUMBER(6) PRIMARY KEY
);

CREATE TABLE AVALIACAO (
    COMENTARIO VARCHAR2(200),
    ID_AVALIACAO NUMBER(6) PRIMARY KEY,
    NOTA NUMBER(1)
);

CREATE TABLE PONTOS_FAV (
    ID_PONTO_INTERESSE NUMBER(6) PRIMARY KEY,
    NOME VARCHAR2(100),
    DESCRICAO VARCHAR2(100),
    LOCALIZACAO NUMBER(6)
);

CREATE TABLE ROTA (
    QUANTIDADE_KW NUMBER,
    TEMPO_MEDIO TIME,
    GASTO_RECARGA NUMBER,
    INICIO NUMBER(6),
    DESTINO NUMBER(6),
    DESCRICAO VARCHAR2(100),
    ID_ROTA NUMBER(6) PRIMARY KEY,
    DISTANCIA NUMBER
);

CREATE TABLE USUARIO_PONTO_FAV (
    FK_USUARIO_ID_USER NUMBER(6),
    FK_PONTOS_FAV_ID_PONTO_INTERESSE NUMBER(6)
);

CREATE TABLE USUARIO_PARADA_ROTA (
    FK_USUARIO_ID_USER NUMBER(6),
    FK_PARADA_ROTA_ID_PARADA NUMBER(6)
);

CREATE TABLE AVALIACAO_USUARIO (
    FK_USUARIO_ID_USER NUMBER(6),
    FK_AVALIACAO_ID_AVALIACAO NUMBER(6)
);

CREATE TABLE USUARIO_PONTO_CARREGAMENTO (
    FK_PONTO_CARREGAMENTO_ID_PONTO NUMBER(6),
    FK_USUARIO_ID_USER NUMBER(6)
);

CREATE TABLE USUARIO_ROTA (
    FK_USUARIO_ID_USER NUMBER(6),
    FK_ROTA_ID_ROTA NUMBER(6)
);

CREATE TABLE ROTA_VEICULO (
    FK_VEICULO_ID_VEICULO NUMBER(6),
    FK_ROTA_ID_ROTA NUMBER(6)
);

CREATE TABLE MODELO (
    ID_MODELO NUMBER(6) PRIMARY KEY,
    FK_MARCA NUMBER(6),
    NOME VARCHAR2(100)
);

CREATE TABLE COR (
    ID_COR NUMBER(6) PRIMARY KEY,
    NOME VARHCAR2(50)
);

CREATE TABLE MARCA (
    ID_MARCA NUMBER(6) PRIMARY KEY,
    NOME VARCHAR2(100)
);

CREATE TABLE TIPO_CONECTOR (
    ID_CONECTOR NUMBER(6) PRIMARY KEY,
    NOME VARCHAR2(50)
);

CREATE TABLE CEP (
    ID_CEP NUMBER(6) PRIMARY KEY,
    FK_BAIRRO NUMBER(6)
);

CREATE TABLE BAIRRO (
    ID_BAIRRO NUMBER(6) PRIMARY KEY,
    NOME VARCHAR2(100),
    FK_CIDADE NUMBER(6)
);

CREATE TABLE CIDADE (
    ID_CIDADE NUMBER(6) PRIMARY KEY,
    NOME VARCHAR2(50),
    FK_ESTADO NUMBER(2)
);

CREATE TABLE ESTADO (
    ID_ESTADO NUMBER(2) PRIMARY KEY,
    UF NUMBER(2)
);

CREATE TABLE ENDERECO (
    ID_ENDERECO NUMBER(6) PRIMARY KEY,
    NOME VARCHAR2(50),
    FK_CEP NUMBER(6)
);

CREATE TABLE STATUS_PONTO (
    ID_STATUS_PONTO NUMBER(6) PRIMARY KEY,
    DESCRICAO VARCHAR2(50)
);
 
ALTER TABLE USUARIO ADD CONSTRAINT FK_USUARIO_2
    FOREIGN KEY (ENDERECO)
    REFERENCES ENDERECO (ID_ENDERECO);
 
ALTER TABLE VEICULO ADD CONSTRAINT FK_VEICULO_2
    FOREIGN KEY (FK_USUARIO_ID_USER)
    REFERENCES USUARIO (ID_USER)
    ON DELETE RESTRICT;
 
ALTER TABLE VEICULO ADD CONSTRAINT FK_VEICULO_3
    FOREIGN KEY (FK_CONECTOR)
    REFERENCES TIPO_CONECTOR (ID_CONECTOR);
 
ALTER TABLE VEICULO ADD CONSTRAINT FK_VEICULO_4
    FOREIGN KEY (FK_COR)
    REFERENCES COR (ID_COR);
 
ALTER TABLE VEICULO ADD CONSTRAINT FK_VEICULO_5
    FOREIGN KEY (MODELO)
    REFERENCES MODELO (ID_MODELO);
 
ALTER TABLE PONTO_CARREGAMENTO ADD CONSTRAINT FK_PONTO_CARREGAMENTO_2
    FOREIGN KEY (LOCALIZACAO)
    REFERENCES ENDERECO (ID_ENDERECO);
 
ALTER TABLE PONTO_CARREGAMENTO ADD CONSTRAINT FK_PONTO_CARREGAMENTO_3
    FOREIGN KEY (DISPONIBILIDADE)
    REFERENCES STATUS_PONTO (ID_STATUS_PONTO);
 
ALTER TABLE PARADA_ROTA ADD CONSTRAINT FK_PARADA_ROTA_2
    FOREIGN KEY (LOCALIZACAO)
    REFERENCES ENDERECO (ID_ENDERECO);
 
ALTER TABLE PONTOS_FAV ADD CONSTRAINT FK_PONTOS_FAV_2
    FOREIGN KEY (LOCALIZACAO)
    REFERENCES ENDERECO (ID_ENDERECO);
 
ALTER TABLE ROTA ADD CONSTRAINT FK_ROTA_2
    FOREIGN KEY (INICIO)
    REFERENCES ENDERECO (ID_ENDERECO);
 
ALTER TABLE ROTA ADD CONSTRAINT FK_ROTA_3
    FOREIGN KEY (DESTINO)
    REFERENCES ENDERECO (ID_ENDERECO);
 
ALTER TABLE USUARIO_PONTO_FAV ADD CONSTRAINT FK_USUARIO_PONTO_FAV_1
    FOREIGN KEY (FK_USUARIO_ID_USER)
    REFERENCES USUARIO (ID_USER)
    ON DELETE SET NULL;
 
ALTER TABLE USUARIO_PONTO_FAV ADD CONSTRAINT FK_USUARIO_PONTO_FAV_2
    FOREIGN KEY (FK_PONTOS_FAV_ID_PONTO_INTERESSE)
    REFERENCES PONTOS_FAV (ID_PONTO_INTERESSE)
    ON DELETE SET NULL;
 
ALTER TABLE USUARIO_PARADA_ROTA ADD CONSTRAINT FK_USUARIO_PARADA_ROTA_1
    FOREIGN KEY (FK_USUARIO_ID_USER)
    REFERENCES USUARIO (ID_USER)
    ON DELETE SET NULL;
 
ALTER TABLE USUARIO_PARADA_ROTA ADD CONSTRAINT FK_USUARIO_PARADA_ROTA_2
    FOREIGN KEY (FK_PARADA_ROTA_ID_PARADA)
    REFERENCES PARADA_ROTA (ID_PARADA)
    ON DELETE SET NULL;
 
ALTER TABLE AVALIACAO_USUARIO ADD CONSTRAINT FK_AVALIACAO_USUARIO_1
    FOREIGN KEY (FK_USUARIO_ID_USER)
    REFERENCES USUARIO (ID_USER)
    ON DELETE SET NULL;
 
ALTER TABLE AVALIACAO_USUARIO ADD CONSTRAINT FK_AVALIACAO_USUARIO_2
    FOREIGN KEY (FK_AVALIACAO_ID_AVALIACAO)
    REFERENCES AVALIACAO (ID_AVALIACAO)
    ON DELETE SET NULL;
 
ALTER TABLE USUARIO_PONTO_CARREGAMENTO ADD CONSTRAINT FK_USUARIO_PONTO_CARREGAMENTO_1
    FOREIGN KEY (FK_PONTO_CARREGAMENTO_ID_PONTO)
    REFERENCES PONTO_CARREGAMENTO (ID_PONTO)
    ON DELETE SET NULL;
 
ALTER TABLE USUARIO_PONTO_CARREGAMENTO ADD CONSTRAINT FK_USUARIO_PONTO_CARREGAMENTO_2
    FOREIGN KEY (FK_USUARIO_ID_USER)
    REFERENCES USUARIO (ID_USER)
    ON DELETE SET NULL;
 
ALTER TABLE USUARIO_ROTA ADD CONSTRAINT FK_USUARIO_ROTA_1
    FOREIGN KEY (FK_USUARIO_ID_USER)
    REFERENCES USUARIO (ID_USER)
    ON DELETE SET NULL;
 
ALTER TABLE USUARIO_ROTA ADD CONSTRAINT FK_USUARIO_ROTA_2
    FOREIGN KEY (FK_ROTA_ID_ROTA)
    REFERENCES ROTA (ID_ROTA)
    ON DELETE SET NULL;
 
ALTER TABLE ROTA_VEICULO ADD CONSTRAINT FK_ROTA_VEICULO_1
    FOREIGN KEY (FK_VEICULO_ID_VEICULO)
    REFERENCES VEICULO (ID_VEICULO)
    ON DELETE SET NULL;
 
ALTER TABLE ROTA_VEICULO ADD CONSTRAINT FK_ROTA_VEICULO_2
    FOREIGN KEY (FK_ROTA_ID_ROTA)
    REFERENCES ROTA (ID_ROTA)
    ON DELETE SET NULL;
 
ALTER TABLE MODELO ADD CONSTRAINT FK_MODELO_2
    FOREIGN KEY (FK_MARCA)
    REFERENCES MARCA (ID_MARCA);
 
ALTER TABLE CEP ADD CONSTRAINT FK_CEP_2
    FOREIGN KEY (FK_BAIRRO)
    REFERENCES BAIRRO (ID_BAIRRO);
 
ALTER TABLE BAIRRO ADD CONSTRAINT FK_BAIRRO_2
    FOREIGN KEY (FK_CIDADE)
    REFERENCES CIDADE (ID_CIDADE);
 
ALTER TABLE CIDADE ADD CONSTRAINT FK_CIDADE_2
    FOREIGN KEY (FK_ESTADO)
    REFERENCES ESTADO (ID_ESTADO);
 
ALTER TABLE ENDERECO ADD CONSTRAINT FK_ENDERECO_1
    FOREIGN KEY (FK_CEP)
    REFERENCES CEP (ID_CEP);