/* Modelo Lógico: */

CREATE TABLE USUARIO (
    ID_USER NUMBER(6) PRIMARY KEY,
    NOME VARCHAR2(100),
    CPF VARCHAR2(11),
    EMAIL VARCHAR2(150),
    SENHA VARCHAR2(50),
    TIPO_USUARIO NUMBER(1),
    NUMERO_RESIDENCIA VARCHAR2(10),
    COMPLEMENTO_ENDERENCO VARCHAR2(100),
    FK_ID_CEP NUMBER(8),
    UNIQUE (CPF, EMAIL)
);

CREATE TABLE VEICULO (
    ID_VEICULO NUMBER(6) PRIMARY KEY,
    MODELO NUMBER(6),
    ANO_FAB NUMBER,
    FK_CONECTOR NUMBER(6),
    PLACA VARCHAR2(10) UNIQUE,
    FK_COR NUMBER(6),
    FK_USUARIO_ID_USER NUMBER(6)
);

CREATE TABLE PONTO_CARREGAMENTO (
    ID_PONTO NUMBER(6) PRIMARY KEY,
    LOCALIZACAO NUMBER(8),
    VALOR_KWH NUMBER,
    FK_STATUS_PONTO NUMBER(6)
);

CREATE TABLE PARADA_ROTA (
    ID_PARADA NUMBER(6) PRIMARY KEY,
    DESCRICAO VARCHAR2(100),
    NUMERO_RESIDENCIA VARCHAR2(10),
    NOME VARCHAR2(100),
    COMPLEMENTO_ENDERECO VARCHAR(100),
    FK_ID_CEP NUMBER(8)
);

CREATE TABLE AVALIACAO (
    ID_AVALIACAO NUMBER(6) PRIMARY KEY,
    COMENTARIO VARCHAR2(200),
    NOTA NUMBER(1),
    DATA_AVALIACAO DATE,
    FK_ID_USUARIO NUMBER(6),
    FK_PONTO_CARRRGAMENTO NUMBER(6)
);

CREATE TABLE PONTO_FAVORITO (
    ID_PONTO_INTERESSE NUMBER(6) PRIMARY KEY,
    NOME VARCHAR2(100),
    DESCRICAO VARCHAR2(100),
    NUMERO_RESIDENCIA VARCHAR2(10),
    COMPLEMENTO_ENDERECO VARCHAR2(100),
    FK_ID_CEP NUMBER(8)
);

CREATE TABLE ROTA (
    ID_ROTA NUMBER(6) PRIMARY KEY,
    DESCRICAO VARCHAR2(100),
    NUMERO_RESIDENCIA VARCHAR2(10),
    COMPLEMENTO_ENDERECO VARCHAR(100),
    TEMPO_MEDIO TIME,
    FK_ID_CEP_INICIO NUMBER(8),
    FK_ID_CEP_DESTINO NUMBER(8)
);

CREATE TABLE USUARIO_PONTO_FAVORITO (
    FK_USUARIO_ID_USER NUMBER(6),
    FK_PONTOS_FAV_ID_PONTO_INTERESSE NUMBER(6)
);

CREATE TABLE VEICULO_PARADA_ROTA (
    FK_VEICULO NUMBER(6),
    FK_PARADA_ROTA_ID_PARADA NUMBER(6)
);

CREATE TABLE VEICULO_PONTO_CARREGAMENTO (
    FK_PONTO_CARREGAMENTO_ID_PONTO NUMBER(6),
    FK_VEICULO NUMBER(6)
);

CREATE TABLE ROTA_VEICULO (
    FK_VEICULO_ID_VEICULO NUMBER(6),
    FK_ROTA_ID_ROTA NUMBER(6)
);

CREATE TABLE MODELO (
    ID_MODELO NUMBER(6) PRIMARY KEY,
    FK_MARCA NUMBER(6),
    NOME VARCHAR2(100)
);

CREATE TABLE COR (
    ID_COR NUMBER(6) PRIMARY KEY,
    NOME VARCHAR2(50)
);

CREATE TABLE MARCA (
    ID_MARCA NUMBER(6) PRIMARY KEY,
    NOME VARCHAR2(100)
);

CREATE TABLE CONECTOR (
    ID_CONECTOR NUMBER(6) PRIMARY KEY,
    NOME VARCHAR2(50)
);

CREATE TABLE CEP (
    ID_CEP NUMBER(8) PRIMARY KEY,
    LOGRADOURO VARCHAR(50),
    FK_BAIRRO NUMBER(6)
);

CREATE TABLE BAIRRO (
    ID_BAIRRO NUMBER(6) PRIMARY KEY,
    NOME VARCHAR2(100),
    FK_CIDADE NUMBER(6)
);

CREATE TABLE CIDADE (
    ID_CIDADE NUMBER(6) PRIMARY KEY,
    NOME VARCHAR2(50),
    FK_ESTADO NUMBER(6)
);

CREATE TABLE ESTADO (
    ID_ESTADO NUMBER(6) PRIMARY KEY,
    UF CHAR(2)
);

CREATE TABLE STATUS_PONTO (
    ID_STATUS_PONTO NUMBER(6) PRIMARY KEY,
    DESCRICAO VARCHAR2(50)
);
 
ALTER TABLE USUARIO ADD CONSTRAINT FK_USUARIO_2
    FOREIGN KEY (FK_ID_CEP)
    REFERENCES CEP (ID_CEP);
 
ALTER TABLE VEICULO ADD CONSTRAINT FK_VEICULO_2
    FOREIGN KEY (FK_USUARIO_ID_USER)
    REFERENCES USUARIO (ID_USER)
    ON DELETE RESTRICT;
 
ALTER TABLE VEICULO ADD CONSTRAINT FK_VEICULO_3
    FOREIGN KEY (FK_CONECTOR)
    REFERENCES CONECTOR (ID_CONECTOR);
 
ALTER TABLE VEICULO ADD CONSTRAINT FK_VEICULO_4
    FOREIGN KEY (FK_COR)
    REFERENCES COR (ID_COR);
 
ALTER TABLE VEICULO ADD CONSTRAINT FK_VEICULO_5
    FOREIGN KEY (MODELO)
    REFERENCES MODELO (ID_MODELO);
 
ALTER TABLE PONTO_CARREGAMENTO ADD CONSTRAINT FK_PONTO_CARREGAMENTO_2
    FOREIGN KEY (LOCALIZACAO)
    REFERENCES CEP (ID_CEP);
 
ALTER TABLE PONTO_CARREGAMENTO ADD CONSTRAINT FK_PONTO_CARREGAMENTO_3
    FOREIGN KEY (FK_STATUS_PONTO)
    REFERENCES STATUS_PONTO (ID_STATUS_PONTO);
 
ALTER TABLE PARADA_ROTA ADD CONSTRAINT FK_PARADA_ROTA_2
    FOREIGN KEY (FK_ID_CEP)
    REFERENCES CEP (ID_CEP);
 
ALTER TABLE AVALIACAO ADD CONSTRAINT FK_AVALIACAO_2
    FOREIGN KEY (FK_PONTO_CARRRGAMENTO)
    REFERENCES PONTO_CARREGAMENTO (ID_PONTO);
 
ALTER TABLE AVALIACAO ADD CONSTRAINT FK_AVALIACAO_3
    FOREIGN KEY (FK_ID_USUARIO)
    REFERENCES USUARIO (ID_USER);
 
ALTER TABLE PONTO_FAVORITO ADD CONSTRAINT FK_PONTO_FAVORITO_2
    FOREIGN KEY (FK_ID_CEP)
    REFERENCES CEP (ID_CEP);
 
ALTER TABLE ROTA ADD CONSTRAINT FK_ROTA_2
    FOREIGN KEY (FK_ID_CEP_INICIO)
    REFERENCES CEP (ID_CEP);
 
ALTER TABLE ROTA ADD CONSTRAINT FK_ROTA_3
    FOREIGN KEY (FK_ID_CEP_DESTINO)
    REFERENCES CEP (ID_CEP);
 
ALTER TABLE USUARIO_PONTO_FAVORITO ADD CONSTRAINT FK_USUARIO_PONTO_FAVORITO_1
    FOREIGN KEY (FK_USUARIO_ID_USER)
    REFERENCES USUARIO (ID_USER)
    ON DELETE SET NULL;
 
ALTER TABLE USUARIO_PONTO_FAVORITO ADD CONSTRAINT FK_USUARIO_PONTO_FAVORITO_2
    FOREIGN KEY (FK_PONTOS_FAV_ID_PONTO_INTERESSE)
    REFERENCES PONTO_FAVORITO (ID_PONTO_INTERESSE)
    ON DELETE SET NULL;
 
ALTER TABLE VEICULO_PARADA_ROTA ADD CONSTRAINT FK_VEICULO_PARADA_ROTA_1
    FOREIGN KEY (FK_VEICULO)
    REFERENCES VEICULO (ID_VEICULO)
    ON DELETE SET NULL;
 
ALTER TABLE VEICULO_PARADA_ROTA ADD CONSTRAINT FK_VEICULO_PARADA_ROTA_2
    FOREIGN KEY (FK_PARADA_ROTA_ID_PARADA)
    REFERENCES PARADA_ROTA (ID_PARADA)
    ON DELETE SET NULL;
 
ALTER TABLE VEICULO_PONTO_CARREGAMENTO ADD CONSTRAINT FK_VEICULO_PONTO_CARREGAMENTO_1
    FOREIGN KEY (FK_PONTO_CARREGAMENTO_ID_PONTO)
    REFERENCES PONTO_CARREGAMENTO (ID_PONTO)
    ON DELETE SET NULL;
 
ALTER TABLE VEICULO_PONTO_CARREGAMENTO ADD CONSTRAINT FK_VEICULO_PONTO_CARREGAMENTO_2
    FOREIGN KEY (FK_VEICULO)
    REFERENCES VEICULO (ID_VEICULO)
    ON DELETE SET NULL;
 
ALTER TABLE ROTA_VEICULO ADD CONSTRAINT FK_ROTA_VEICULO_1
    FOREIGN KEY (FK_VEICULO_ID_VEICULO)
    REFERENCES VEICULO (ID_VEICULO)
    ON DELETE SET NULL;
 
ALTER TABLE ROTA_VEICULO ADD CONSTRAINT FK_ROTA_VEICULO_2
    FOREIGN KEY (FK_ROTA_ID_ROTA)
    REFERENCES ROTA (ID_ROTA)
    ON DELETE SET NULL;
 
ALTER TABLE MODELO ADD CONSTRAINT FK_MODELO_2
    FOREIGN KEY (FK_MARCA)
    REFERENCES MARCA (ID_MARCA);
 
ALTER TABLE CEP ADD CONSTRAINT FK_CEP_2
    FOREIGN KEY (FK_BAIRRO)
    REFERENCES BAIRRO (ID_BAIRRO);
 
ALTER TABLE BAIRRO ADD CONSTRAINT FK_BAIRRO_2
    FOREIGN KEY (FK_CIDADE)
    REFERENCES CIDADE (ID_CIDADE);
 
ALTER TABLE CIDADE ADD CONSTRAINT FK_CIDADE_2
    FOREIGN KEY (FK_ESTADO)
    REFERENCES ESTADO (ID_ESTADO);